### ISSUE TITLE
hystrix max concurrent connection exception

### ISSUE THREAD

**Issue by bsushant-athena** [Netflix/Hystrix#1709]
When I hit 
http://10.8.110.83:18888/hystrix.stream

> I'm getting this error:
> There was an unexpected error (type=Service Unavailable, status=503).
> MaxConcurrentConnections reached: 5

```
Configuration:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  threadpool:
    default:
      coreSize: 50

turbine:
  aggregator:
    clusterConfig: GATEWAY
  appConfig: GATEWAY
```

I'm able to see hystrix metrics. But this error ??
